### ISSUE TITLE
Benchmarks vary according to the execution order and without jiffy

### ISSUE THREAD

**Issue by williamthome** [saleyn/simdjsone#4]
Regarding my comment at the Erlang Forums, I was making a mistake in my environment.

By running `$ make benchmark` I receive a great variation of the results by changing the execution order of the libs/functions.
It's strange because the tests are spawned but the results are much different to me.

For simplification, all of the results are just for the esad.json file (second test).

## Current order

```erlang
% simjson.erl, line 135 
L = [
    {"simdjsone", fun(B) -> simdjson:decode(B)             end},
    {"jiffy",     fun(B) -> jiffy:decode(B, [return_maps]) end},
    {"thoas",     fun(B) -> {ok, R} = thoas:decode(B),  R  end},
    {"euneus",    fun(B) -> {ok, R} = euneus:decode(B), R  end}
 ]
```

```console
# Run 1
=== Benchmark (file size: 1.3K) ===
   simdjsone:     10.480us
       jiffy:     17.530us
       thoas:     17.760us
      euneus:     26.280us

# Run 2
=== Benchmark (file size: 1.3K) ===
   simdjsone:     10.300us
       thoas:     16.900us
       jiffy:     17.700us
      euneus:     23.770us

# Run 3
=== Benchmark (file size: 1.3K) ===
   simdjsone:      8.810us
       jiffy:     16.070us
       thoas:     19.630us
      euneus:     22.120us
```

## Reverse order

```erlang
L = [
    {"euneus",    fun(B) -> {ok, R} = euneus:decode(B), R  end},
    {"thoas",     fun(B) -> {ok, R} = thoas:decode(B),  R  end},
    {"jiffy",     fun(B) -> jiffy:decode(B, [return_maps]) end},
    {"simdjsone", fun(B) -> simdjson:decode(B)             end}
 ]
```

```console
# Run1 
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.260us
      euneus:     16.570us
       jiffy:     24.310us
       thoas:     29.410us

# Run 2
=== Benchmark (file size: 1.3K) ===
   simdjsone:     15.190us
      euneus:     34.170us
       jiffy:     45.060us
       thoas:     59.650us

# Run 3
=== Benchmark (file size: 1.3K) ===
   simdjsone:      8.460us
      euneus:     20.370us
       jiffy:     25.110us
       thoas:     41.580us
```

## Testing without jiffy

The results are much different when testing without jiffy.

```console
# Run 1
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.160us
      euneus:     13.600us
       thoas:     17.520us

# Run 2
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.250us
      euneus:     14.270us
       thoas:     17.080us

# Run 3
=== Benchmark (file size: 1.3K) ===
   simdjsone:      8.870us
      euneus:     13.890us
       thoas:     15.680us
```

I'm not saying that the benchmarks are wrong, but I'm trying to understand the results and maybe I then improve Euneus decoding :slightly_smiling_face:

**Comment by saleyn** [comment]
I think it was due to the call to garbage_collect. I removed it. Please try again.

**Comment by williamthome** [comment]
Thank you for taking a look at this.

The results continue to have a certain variation/deviation:

 ```console
# Run 1
=== Benchmark (file size: 1.3K) ===
   simdjsone:     10.170us
       jiffy:     15.190us
      euneus:     16.450us
       thoas:     19.680us

# Run 2
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.130us
       jiffy:     16.400us
       thoas:     16.900us
      euneus:     27.280us

# Run 3
=== Benchmark (file size: 1.3K) ===
   simdjsone:      8.340us
      euneus:     16.360us
       jiffy:     22.850us
       thoas:     29.960us
```

## Without jiffy

```console
# Run1
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.450us
      euneus:     13.280us
       thoas:     16.650us

# Run 2
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.660us
      euneus:     14.570us
       thoas:     16.590us

# Run 3
=== Benchmark (file size: 1.3K) ===
   simdjsone:     11.130us
      euneus:     14.930us
       thoas:     16.550us
```

Maybe it is related to [this topic](https://elixirforum.com/t/understanding-concurrent-tasks-in-context-of-beam-schedulers-cpu-cores/30938)?

Benchee creator posted this note [here](https://elixirforum.com/t/looking-for-help-with-poor-ecto-query-performance/25476/28?u=williamthome):
> To avoid garbage influencing your measurements you could use hooks with after_each: fn _ -> :erlang.garbage_collect() end however those collects take a long time so the total number of samples/work done will go down by A LOT.

I'm not sure, but maybe the GC makes sense in that case.

I changed the test spawn to this:
```erlang
% line 142
Tasks = [{Name, spawn(fun() ->
              P ! {Name, tc(N, fun() -> erlang:garbage_collect(), Fun(Bin) end)}
            end)} || {Name, Fun} <- L],
```

The results, but a great deviation always occurs:

```
# Run 1
=== Benchmark (file size: 1.3K) ===
   simdjsone:      9.130us
      euneus:     13.850us
       thoas:     17.750us
       jiffy:     28.400us

# Run 2
=== Benchmark (file size: 1.3K) ===
      euneus:     15.170us
   simdjsone:     16.850us
       thoas:     23.490us
       jiffy:     34.810us

# Run 3
=== Benchmark (file size: 1.3K) ===
   simdjsone:      8.470us
       jiffy:     15.310us
       thoas:     16.600us
      euneus:     21.180us

# Run 4
=== Benchmark (file size: 1.3K) ===
   simdjsone:      8.840us
       jiffy:     14.320us
      euneus:     17.160us
       thoas:     18.480us

# Run 5
=== Benchmark (file size: 1.3K) ===
   simdjsone:     10.100us
      euneus:     16.480us
       thoas:     19.780us
       jiffy:     30.380us
```

I see it as hard to say what's the "real" result. 
BTW, I think the results of euneus are not related to its decode function.

**Comment by saleyn** [comment]
I think when you call the garbage_collect inside a spawn in each iteration of a test it has the timing effect on the outcome, which is affecting the results.

**Comment by williamthome** [comment]
Sorry for the delay. I forgot about this issue.

> I think when you call the garbage_collect inside a spawn in each iteration of a test it has the timing effect on the outcome, which is affecting the results.

I agree my implementation is wrong, but the results have a significant deviation with and without `erlang:garbage_collect/0`.
The deviation is reduced only when `$ make benchmark` is run without `jiffy`. Do you have any thoughts on why this is happening?

**Comment by saleyn** [comment]
jiffy executes on a dirty scheduler, so I suppose the synchronization of switching context between the main and dirty scheduler has some locking overhead with adverse effect.  This is just a guess.

**Comment by williamthome** [comment]
Hmm, your guess can be correct.
I wonder if there is something to do about this. I'll ignore these benchmarks for now.
Feel free to close this issue if you think there is nothing to do. 
Thank you!
