### ISSUE TITLE
Compilation fails on an M1 mac

### ISSUE THREAD

**Issue by michalmuskala** [saleyn/simdjsone#6]
Adding the dependency to `mix.exs` and running `mix deps.get && mix build` fails with:

```
c++ -pie -DSIMDJSON_DISABLE_DEPRECATED_API -fPIC -finline-functions -Wall -std=c++20 -O3 -DNDEBUG -I/Users/micmus/homebrew/Cellar/erlang/26.2.1/lib/erlang/erts-14.2.1/include -I/Users/micmus/homebrew/Cellar/erlang/26.2.1/lib/erlang/lib/erl_interface-5.5/include  -c -o simdjson_nif.o simdjson_nif.cpp
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
simdjson_nif.cpp:413:8: error: no matching function for call to 'enif_get_long'
  if (!enif_get_long(env, argv[0], &n))
       ^~~~~~~~~~~~~
/Users/micmus/homebrew/Cellar/erlang/26.2.1/lib/erlang/erts-14.2.1/include/erl_nif_api_funcs.h:104:27: note: candidate function not viable: no known conversion from 'int64_t *' (aka 'long long *') to 'long *' for 3rd argument
ERL_NIF_API_FUNC_DECL(int,enif_get_long,(ErlNifEnv*, ERL_NIF_TERM term, long* ip));
                          ^
/Users/micmus/homebrew/Cellar/erlang/26.2.1/lib/erlang/erts-14.2.1/include/erl_nif.h:369:71: note: expanded from macro 'ERL_NIF_API_FUNC_DECL'
#  define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) extern RET_TYPE NAME ARGS
                                                                      ^
1 error generated.
make: *** [simdjson_nif.o] Error 1
===> Hook for compile failed!
```

**Comment by saleyn** [comment]
@michalmuskala, could you try this again?  The issue was platform specific and didn't surface on Linux x64.

**Comment by saleyn** [comment]
I'd like to include your library in the benchmark.  Do you have it implemented in a stand-alone project that can be built with OTP26?

**Comment by michalmuskala** [comment]
Performance with OTP 26 will be worse than with 27 - the new implementation takes advantage of certain new optimisations in the compiler/runtime present in OTP 27.

**Comment by saleyn** [comment]
@michalmuskala, did it compile for you using the master branch?

**Comment by crkent** [comment]
Thanks for the package! I replicated this issue on an M2 Mac, when pulling the most recent version from hex. The issue was resolved when I pulled the package directly from the master branch.

Will the hex version be updated at some point?

**Comment by saleyn** [comment]
I pushed an updated version to hex https://hex.pm/packages/simdjsone
