### ISSUE TITLE
Crash during simdjson:decode/1 perf testing

### ISSUE THREAD

**Issue by Zabrane** [saleyn/simdjsone#7]
Hi @saleyn 

I'm getting a `Segmentation fault: 11` when trying to speed benchmark the latest `simdjsone` (main branch) against the new default `Erlang 27.0.1` [json](https://erlang.org/documentation/doc-15.0-rc3/lib/stdlib-6.0/doc/html/json.html) parser using the excellent [erlperf](https://github.com/max-au/erlperf);

```bash
$ erlperf 'runner(X)->simdjson:decode(X).' 'runner(X)->json:decode(X).' \
        --init_runner_all '{ok,Bin}=file:read_file("x.json"),Bin.' \
        --warmup 1 --concurrency 8 --samples 10 -pa _build/default/lib/simdjson/ebin --report full
```        

Here is a simple JSON file to test:
[x.json](https://github.com/user-attachments/files/16646201/x.json)

The same benchmark perfectly works if I use [jiffy](https://github.com/davisp/jiffy) (NIF based json decoder/encoder) instead of `simdjsone`.

Further testing have shown that the issue is in the `decoding` because the `encoding` works as expected with no crash:
```bash
$ erlperf 'runner(X)->simdjson:encode(X).' 'runner(X)->json:encode(X).' \
        --init_runner_all '{ok, Bin}=file:read_file("x.json"),json:decode(Bin).' \
        --warmup 1 --concurrency 8 --samples 10 -pa _build/default/lib/simdjson/ebin --report full
runner(X)->json:encode(X).          8        10   1886 Ki    8.90%   1969 Ki  2060 Ki    4241 ns   100%
runner(X)->simdjson:encode(X).      8        10    991 Ki    8.80%   1015 Ki  1091 Ki    8072 ns    53%
```

Any idea why  it crashes?
Many thanks

**Comment by saleyn** [comment]
Would you be able to reproduce this in the shell when not using erlprof?  I was trying this but it doesn't reproduce the error:
```
1> {ok, Bin} = file:read_file("x.json").
2>  lists:foreach(fun(I) -> spawn(fun() -> simdjson:decode(Bin), io:format("Done: ~w\n", [I]) end) end, lists:seq(1, 1000)).
```

**Comment by Zabrane** [comment]
> Would you be able to reproduce this in the shell when not using erlprof? I was trying this but it doesn't reproduce the error:
> 
> ```
> 1> {ok, Bin} = file:read_file("x.json").
> 2>  lists:foreach(fun(I) -> spawn(fun() -> simdjson:decode(Bin), io:format("Done: ~w\n", [I]) end) end, lists:seq(1, 1000)).
> ```

@saleyn  it worked, no crash :
```
[...]
Done: 444
Done: 439
Done: 413
Done: 330
Done: 329
Done: 423
Done: 457
Done: 460
```

Let me try this on a brand new machine to see how it goes.

In the meantime, do you get the same numbers as me when benchmarking the `encoding` speed?

1. How come that `json:encode/1` in pure Erlang is faster than `simdjson:encode/1` (NIF) by an order of magnitude?
2. Are you aware of an alternative way to test the speed?

**Comment by Zabrane** [comment]
This is the error on macOS M1 when running the same `decoding` benchmark.

```plain
OS : MacOS
CPU: Apple M1
VM : Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] 

{{badarg,<<"3">>},
      [{simdjson,decode,
                 [<<"{\n    \"quiz\": {\n        \"sport\": {\n            \"q1\": {\n                \"question\": \"Which one is correct team name in NBA?\",\n                \"options\": [\n                    \"New York Bulls\",\n                    \"Los Angeles Kings\",\n                    \"Golden State Warriros\",\n                    \"Huston Rocket\"\n                ],\n                \"answer\": \"Huston Rocket\"\n            }\n        },\n        \"maths\": {\n            \"q1\": {\n                \"question\": \"5 + 7 = ?\",\n                \"options\": [\n                    \"10\",\n                    \"11\",\n                    \"12\",\n                    \"13\"\n                ],\n                \"answer\": \"12\"\n            },\n            \"q2\": {\n                \"question\": \"12 - 8 = ?\",\n                \"options\": [\n                    \"1\",\n                    \"2\",\n                    \"3\",\n                    \"4\"\n                ],\n                \"answer\": \"4\"\n            }\n        }\n    }\n}\n">>],
                 []},
       {job_69464_1286,job_69464_1286,1,
                       [{file,"job_69464_1286.erl"},{line,2}]}]}
```

<img width="1162" alt="Screenshot 2024-08-19 at 17 56 21" src="https://github.com/user-attachments/assets/19b462f4-550d-41e9-a3aa-b770a41a589a">

**Comment by Zabrane** [comment]
Hi @saleyn 

Here is a `decode` test which crashes on another `macOS intel (x86_64)`.

```bash
$ erl
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [dtrace]

$ sw_vers | head -2
ProductName:	macOS
ProductVersion:	12.3.1

$ uname -a
Darwin xxx_redacted_xxx.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

$ erlperf 'runner(X)->simdjson:decode(X).' 'runner(X)->json:decode(X).' \
        --init_runner_all '{ok,Bin}=file:read_file("x.json"),Bin.' \
        --warmup 1 --concurrency 8 --samples 10 -pa _build/default/lib/simdjson/ebin --report full
```

![Screenshot 2024-08-19 at 21 11 29](https://github.com/user-attachments/assets/812773be-cccf-4876-8297-f8dbcf8c0222)

**Comment by saleyn** [comment]
> 
> In the meantime, do you get the same numbers as me when benchmarking the `encoding` speed?
> 
> 1. How come that `json:encode/1` in pure Erlang is faster than `simdjson:encode/1` (NIF) by an order of magnitude?

I get different numbers of my machine:
```
$ erlperf 'run(X)->simdjson:encode(X).' 'run(X)->json:encode(X).' --init_runner_all '{ok,Bin}=file:read_file("x.json"),Bin.' --warmup 1 --concurrency 8 --samples 10 -pa _build/default/lib/simdjsone/ebin --report full
OS : Linux
CPU: AMD Ryzen 9 6900HX with Radeon Graphics
VM : Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Code                            ||   Samples       Avg   StdDev    Median      P99  Iteration    Rel
run(X)->simdjson:encode(X).      8        10   1269 Ki    2.18%   1287 Ki  1293 Ki    6306 ns   100%
run(X)->json:encode(X).          8        10    973 Ki    1.79%    981 Ki   995 Ki    8223 ns    77%
```

Note that the encoding speed should be comparable to `jiffy` as it's nearly the same implementation. The project was optimized for the decoding speed.

> 2. Are you aware of an alternative way to test the speed?

You can try `make test`

**Comment by Zabrane** [comment]
Hi @saleyn 

This is definitely a bug on the `decoding` part. Here is a test on `Ubuntu 22.04 LTS` using Erlang 27.0.1
```bash
$ erlperf 'runner(X)->simdjson:decode(X).' 'runner(X)->json:decode(X).' \
        --init_runner_all '{ok,Bin}=file:read_file("x.json"),Bin.' \
        --warmup 1 --concurrency 8 --samples 10 -pa _build/default/lib/simdjson/ebin --report full
        
33909 Segmentation fault      (core dumped)

$ ls -lah
.rw-r----- 18M zab 21 Aug 04:44 /var/crash/_opt_erlang_27.0.1_erts-15.0.1_bin_beam.smp.1000.crash
```

Strange that you weren't able to reproduce it as I do on 4 different machines.

**Comment by saleyn** [comment]
I managed to reproduce it, and fix the bug. Please check again using the master branch:
```
$ erlperf 'runner(X)->simdjson:decode(X).' 'runner(X)->json:decode(X).'         --init_runner_all '{ok,Bin}=file:read_file("x.json"),Bin.'         --warmup 1 --concurrency 8 --samples 2 -pa _build/default/lib/simdjsone/ebin --report full
OS : Linux
CPU: AMD Ryzen 9 6900HX with Radeon Graphics
VM : Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Code                               ||   Samples       Avg   StdDev    Median      P99  Iteration    Rel
runner(X)->simdjson:decode(X).      8         2   2089 Ki    0.10%   2088 Ki  2091 Ki    3831 ns   100%
runner(X)->json:decode(X).          8         2    986 Ki    0.44%    983 Ki   989 Ki    8115 ns    47%
```

**Comment by Zabrane** [comment]
@saleyn The fix worked and the performances are much better. `simdjson` is faster than other alternatives.
Many thanks.

**Comment by saleyn** [comment]
Thanks for reporting the issue!
